/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Login1Component {
        "boton": string;
        "buttonTitle": string;
        "password": string;
        "socialTitle": string;
        "titulo": string;
        "username": string;
        "usernameIcon": string;
    }
    interface Login2Component {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLLogin1ComponentElement extends Components.Login1Component, HTMLStencilElement {
    }
    var HTMLLogin1ComponentElement: {
        prototype: HTMLLogin1ComponentElement;
        new (): HTMLLogin1ComponentElement;
    };
    interface HTMLLogin2ComponentElement extends Components.Login2Component, HTMLStencilElement {
    }
    var HTMLLogin2ComponentElement: {
        prototype: HTMLLogin2ComponentElement;
        new (): HTMLLogin2ComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "login1-component": HTMLLogin1ComponentElement;
        "login2-component": HTMLLogin2ComponentElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface Login1Component {
        "boton"?: string;
        "buttonTitle"?: string;
        "password"?: string;
        "socialTitle"?: string;
        "titulo"?: string;
        "username"?: string;
        "usernameIcon"?: string;
    }
    interface Login2Component {
        "onLogin"?: (event: CustomEvent<any>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "login1-component": Login1Component;
        "login2-component": Login2Component;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "login1-component": LocalJSX.Login1Component & JSXBase.HTMLAttributes<HTMLLogin1ComponentElement>;
            "login2-component": LocalJSX.Login2Component & JSXBase.HTMLAttributes<HTMLLogin2ComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
